#:kivy 1.0.9

<MassVariantParticle>:
    size: 10, 10 
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size 

<SpongyWallParticle>:
    size: 100, 100
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size
       

<ParticleSim>:
    
    canvas:
        Rectangle:
            pos: self.center_x, self.height-1
            size: self.width, 5
    



        